### PR TITLE
Fix client hanging up by skipping ready check when client is already ready

### PR DESCRIPTION
**Pull request by 00I0I0I0**
fixed issue #9
don't wait for the client to be ready if it is already ready

### CODE REVIEW

**Comment by synzen** [comment]
That's interesting, thanks for the PR. But were you able to effectively reproduce and verify that it does fix #9 ? Or was this a hunch?

**Comment by tytan652** [comment]
From what he said to me, we were also stuck at `Waiting for client to be ready...` in the logs.

**Comment by 00I0I0I0** [comment]
The probleme was that depending on the system on which the bot is running, the client is or not ready when reaching the line `await once(this.client, 'ready')` and if it is already ready the event is never triggered and the program is stucked. On the slowest systems the bot is always working, on the fastest one it is never working and on some intermediate systems it is sometimes working and sometimes not, that's why I have linked this bug to the issue #9

**Comment by synzen** [comment]
Very well, thanks again.

**Pull request merged**
